/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/forecasts": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Forecast */
        readonly get: operations["get_forecast_api_v1_forecasts_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Liveness */
        readonly get: operations["liveness_api_v1_health_live_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Readiness */
        readonly get: operations["readiness_api_v1_health_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/routes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Routes */
        readonly get: operations["list_routes_api_v1_routes_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/scenarios/evaluate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Evaluate Scenario */
        readonly post: operations["evaluate_scenario_api_v1_scenarios_evaluate_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ForecastHorizon
         * @enum {string}
         */
        readonly ForecastHorizon: "day" | "month" | "year";
        /** ForecastPointResponse */
        readonly ForecastPointResponse: {
            /** Capacity */
            readonly capacity: number;
            /** Lower Bound */
            readonly lower_bound: number;
            /** Predicted Passengers */
            readonly predicted_passengers: number;
            /**
             * Timestamp
             * Format: date-time
             */
            readonly timestamp: string;
            /** Upper Bound */
            readonly upper_bound: number;
        };
        /** ForecastResponse */
        readonly ForecastResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            readonly generated_at: string;
            readonly horizon: components["schemas"]["ForecastHorizon"];
            /** Model Version */
            readonly model_version: string;
            /** Peak Load Percent */
            readonly peak_load_percent: number;
            /** Peak Passengers */
            readonly peak_passengers: number;
            /** Points */
            readonly points: readonly components["schemas"]["ForecastPointResponse"][];
            readonly route: components["schemas"]["RouteResponse"];
            /** Stops */
            readonly stops: readonly components["schemas"]["StopLoadResponse"][];
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** RouteResponse */
        readonly RouteResponse: {
            /** Color */
            readonly color: string;
            /** Id */
            readonly id: number;
            /** Name */
            readonly name: string;
            /** Number */
            readonly number: string;
        };
        /** ScenarioRequest */
        readonly ScenarioRequest: {
            /**
             * Additional Vehicles
             * @default 0
             */
            readonly additional_vehicles: number;
            /**
             * Demand Change Percent
             * @default 0
             */
            readonly demand_change_percent: number;
            /** @default day */
            readonly horizon: components["schemas"]["ForecastHorizon"];
            /**
             * Interval Change Percent
             * @default 0
             */
            readonly interval_change_percent: number;
            /** Route Id */
            readonly route_id: number;
        };
        /** ScenarioResponse */
        readonly ScenarioResponse: {
            /** Affected Stops */
            readonly affected_stops: readonly components["schemas"]["StopLoadResponse"][];
            /** Baseline Peak Load Percent */
            readonly baseline_peak_load_percent: number;
            /** Capacity Delta */
            readonly capacity_delta: number;
            /** Passenger Delta */
            readonly passenger_delta: number;
            /** Scenario Peak Load Percent */
            readonly scenario_peak_load_percent: number;
            /** Solver Version */
            readonly solver_version: string;
        };
        /** StopLoadResponse */
        readonly StopLoadResponse: {
            /** Id */
            readonly id: number;
            /** Latitude */
            readonly latitude: number;
            /** Load Percent */
            readonly load_percent: number;
            /** Longitude */
            readonly longitude: number;
            /** Name */
            readonly name: string;
            /** Predicted Passengers */
            readonly predicted_passengers: number;
            /** Sequence */
            readonly sequence: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly get_forecast_api_v1_forecasts_get: {
        readonly parameters: {
            readonly query: {
                readonly horizon?: components["schemas"]["ForecastHorizon"];
                readonly route_id: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly liveness_api_v1_health_live_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly readiness_api_v1_health_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly list_routes_api_v1_routes_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["RouteResponse"][];
                };
            };
        };
    };
    readonly evaluate_scenario_api_v1_scenarios_evaluate_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
